name: Metrics
on:
  workflow_dispatch:    # 수동 실행
  schedule:
    - cron: "0 17 * * *"  # 한국시간 새벽 2시
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.traffic.svg
          base: header, activity, community, repositories
          plugin_traffic: yes