name: Metrics
on:
  workflow_dispatch:    # 수동 실행
  push: {branches: ["master", "main"]}
  schedule:
    - cron: "0 17 * * *"  # 한국시간 새벽 2시
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Repositories traffic
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.traffic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_traffic: yes